### ISSUE TITLE
Doesn't remain signed in

### ISSUE THREAD

**Issue by ryanaltvater** [musicplayer-io/redditmusicplayer#21]
I've logged in a couple times, allowing access to my account. When I refresh, it says "Log In" again as if I'm not signed in.

**Comment by Illyism** [comment]
Seems to work for me. Try this domain: https://reddit.music.player.il.ly/

I don't have HTTPS yet on musicplayer.io that's why I redirect to that one.

**Comment by ryanaltvater** [comment]
Yeah, seems to work now after clearing my cache. Odd.
