### ISSUE TITLE
Clicking on a playlist under "My Subreddit Playlist" deletes it

### ISSUE THREAD

**Issue by ryanaltvater** [musicplayer-io/redditmusicplayer#22]
When I click on one of my subreddit playlists, it switches to that playlist, deletes it from the list, and re-adds "Listen To This" if there aren't any playlists in the list anymore.

**Comment by Illyism** [comment]
Yes, I always want to show a default sub if the user has none selected.

And that's the idea. So I think it works as intended.

**Comment by ryanaltvater** [comment]
Makes sense, unless I'm logged in and purposely remove that default. At that point it should stay removed even if my list of playlists is empty.

There's also still the issue with clicking a playlist and it disappearing.
