### ISSUE TITLE
Bandcamp player doesn't load

### ISSUE THREAD

**Issue by jscheel** [musicplayer-io/redditmusicplayer#33]
I'll try to take a look at this later, but bandcamp player doesn't appear to be working. It keeps whatever the last song was, but loads the new information about the song you clicked.

**Comment by Illyism** [comment]
I think they permanently disabled their API. So it seems.

**Comment by jscheel** [comment]
Ah, @Illyism, you are right (https://bandcamp.com/developer). That's a shame. I hate seeing platforms shutting down their developer access.

**Comment by jscheel** [comment]
Perhaps a better task for this issue would be to unload the existing player when a bandcamp song is selected. Maybe even include a little bar that explains the issue and asks people to tell bandcamp what they think of it :smiling_imp:

**Comment by Illyism** [comment]
Alright, I'll look for possible fixes around this. Otherwise, it's rolling without Bandcamp.

**Comment by Illyism** [comment]
Removed support for bandcamp.
