### ISSUE TITLE
The Player freeze when you type anything in "Custom Subreddit" field .

### ISSUE THREAD

**Issue by AhmedKamal20** [musicplayer-io/redditmusicplayer#52]
The Player freeze when you type anything in "Custom Subreddit" field , and stop the track been played a couple of seconds, and you can't do anything about it until this couple of seconds finish.

**Comment by Illyism** [comment]
I can't replicate this. What operating system and browser version are you using?

**Comment by AhmedKamal20** [comment]
Google Chrome Version 46.0.2490.71 / Ubuntu 14.04 / 64-bit

**Comment by AhmedKamal20** [comment]
I Just try it now on Firefox, And it works fine !
