### ISSUE TITLE
"This sound can’t be played outside of SoundCloud"

### ISSUE THREAD

**Issue by hhu94** [musicplayer-io/redditmusicplayer#56]
This error makes the player stop. It might be a good idea to handle this error and skip to the next link. I would love to help out and do it myself but I don't know coffee script.

**Comment by Illyism** [comment]
Yeah, CoffeeScript is starting to become a drag as I want to transition to the newer ES standard with Babel. But I'm not sure if the time investment would be beneficial that much.

I'll take a look, thanks!

**Comment by Illyism** [comment]
Can you provide me an example of a subreddit where such a link would appear?
You can try on the beta channel if this fix works: https://beta.musicplayer.io/

**Comment by hhu94** [comment]
It works! In /r/Nujabes there is a link titled "[Original] Nujabes / J Dilla / Funky DL Tribute/Mashup I created". Now it correctly skips it. Thanks :)
