### ISSUE TITLE
soundcloud sound is always lower than played in the sourndcloud website

### ISSUE THREAD

**Issue by aliceinwire** [musicplayer-io/redditmusicplayer#67]
when playing soundcloud music on reddit musicplayer, the sound come out much lower than listening directly from the soundcloud website.
The audio level on redditmusicplayer also dosen't work with soundcloud.

**Comment by evoactivity** [comment]
+1

**Comment by arteepa** [comment]
+1

**Comment by evoactivity** [comment]
Seems ok now, must have been on soundclouds end?

@aliceinwire @arteepa is it ok for you two as well?

**Comment by Illyism** [comment]
It's definitely on Soundcloud's end...

**Comment by aliceinwire** [comment]
is still problem for me

**Comment by ulyssesp** [comment]
PR up to fix. I obviously can't update the main site, but it works locally if you want to clone in the meantime.

**Comment by Illyism** [comment]
@ulyssesp It's online. Thank you for the fix.
