### ISSUE TITLE
Propose Logo/Icon

### ISSUE THREAD

**Issue by mirzazulfan** [musicplayer-io/redditmusicplayer#73]
Hi. I'm graphic disigner. I would like to know if you are interested that I make a logo for your project? If you allowed me, i"ll make logo for your project and it's free.

**Comment by Illyism** [comment]
Sure!

**Comment by mirzazulfan** [comment]
Hi @Illyism .. Sorry for late reply, I've designed a logo for this awesome project. Tell me if you need some change i'll fix it. 
![reddit](https://user-images.githubusercontent.com/36124339/41480501-e472100e-70f8-11e8-99f7-bafe9c1a9dbc.png)

Mockup
![untitled-1](https://user-images.githubusercontent.com/36124339/41480520-f0d7922e-70f8-11e8-941a-93eaaae8e64d.png)

**Comment by Illyism** [comment]
Cool. Can you explain your thought behind it?

**Comment by mirzazulfan** [comment]
If you liked it, i'll send you files and pr. 
![ideajpg](https://user-images.githubusercontent.com/36124339/41495372-1d0adfc4-7115-11e8-8f91-7448e1b8432b.jpg)
What do you think @Illyism ?
